/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconLogosEslint: typeof import('~icons/logos/eslint.jsx')['default']
  const IconLogosUnocss: typeof import('~icons/logos/unocss.jsx')['default']
  const IconLogosVitejs: typeof import('~icons/logos/vitejs.jsx')['default']
  const IconSimpleIconsIconify: typeof import('~icons/simple-icons/iconify.jsx')['default']
}
